from __future__ import annotations

from aiogram.fsm.state import State, StatesGroup


class QuestionnaireStates(StatesGroup):
    start = State()
    q01_name = State()
    q02_age = State()
    q03_sex = State()
    q04_height = State()
    q05_weight = State()
    q06_waist = State()
    q07_primary_goal = State()
    q08_secondary_goals = State()
    q09_desired_result = State()
    q10_timeframe = State()
    q11_experience = State()
    q12_current_frequency = State()
    q13_current_activity = State()
    q14_current_exercises = State()
    q15_working_weights = State()
    q16_location = State()
    q17_gym_name = State()
    q18_equipment = State()
    q19_equipment_photos = State()
    q18b_home_equipment = State()
    q20_sessions_per_week = State()
    q21_preferred_days = State()
    q22_session_duration = State()
    q23_preferred_time = State()
    q24_has_limitations = State()
    q25_limitation_categories = State()
    q27_movements_to_avoid = State()
    q28_medical_clearance = State()
    q28_doctor_recommendations = State()
    q29_preferred_exercises = State()
    q30_disliked_exercises = State()
    q31_exercise_goals = State()
    q32_daily_activity = State()
    q33_cardio_preference = State()
    q34_cardio_notes = State()
    q35_schedule_constraints = State()
    q36_free_text = State()
    review = State()
    confirm = State()
